name: CI Build UefiBootLogProcessor

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Build
      run: dotnet build --configuration ${{matrix.configuration}}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: BuildPackage-${{matrix.configuration}}
        path: bin/${{matrix.configuration}}/net8.0-windows
